name: Announcer
version: '${project.version}'
main: club.endi.announcer.AnnouncerPlugin
api-version: '1.20'

commands:
  announce:
    description: Make An Announcement
    usage: /<command> <text>
    permission: simpleannouncer.announce
    permission-message: §cYou do not have the permission to do that!
