name: Announcer
version: '1.0-SNAPSHOT'
main: club.endi.announcer.AnnouncerPlugin
api-version: '1.20'

commands:
  announce:
    description: tee ilmoitus
    usage: /<command> <text>
    permission: end.announce
    permission-message: Sinulla ei ole oikeutta tehdä tuota!
