name: Java CI with Maven

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Move artifact
        run: |
          artifact=$(find target -name 'Announcer-*.jar' -print -quit)
          if [ -n "$artifact" ]; then
            echo "Moving artifact: $artifact to target/Announcer.jar"
            mv "$artifact" target/Announcer.jar
          else
            echo "No matching artifact found"
            exit 1
          fi
        shell: bash

      - name: Upload moved artifact
        uses: actions/upload-artifact@v3
        with:
          path: target/Announcer.jar
          name: Announcer.jar